services:
  db:
    container_name: db
    restart: always
    image: postgres:15.2
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    expose:
      - "${POSTGRES_PORT}"
    command:
      - "postgres"
      - "-c"
      - "port=${POSTGRES_PORT}"

  api:
    build:
      context: .
      dockerfile: Dockerfile
      container_name: api
      env_file:
        - .env
      ports:
        - ${API_PORT}:${API_PORT}
      depends_on:
        - db

